import Card from '@/components/home/Card'
import Nav from '@/components/home/Nav'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>postcases</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=' w-full h-max flex flex-col '>
        <Nav />
        <div className=' w-11/12 h-max bg-slate-100  mt-5  self-center backdrop-blur-3xl flex flex-col'>
          <Card />
          <Card />
          <Card />
        </div>
      </main>
    </>
  )
}
