
import Nav from '../components/Nav'
import Head from 'next/head'
import SearchOutlinedIcon from '@mui/icons-material/SearchOutlined';
import Sidebar from "../components/userdashboard/Sidebar";
import BlogCard from '../components/index/BlogCard';
import Link from 'next/link';
import ModeEditOutlineOutlinedIcon from '@mui/icons-material/ModeEditOutlineOutlined';

export default function Home() {
    return (
        <>
            <Head>
                <title>postcases</title>

                <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.15.1/devicon.min.css" />
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='     min-w-fit  h-max flex flex-col'>
                <Nav />
                <div className='w-full h-max  b flex justify-center mt-5   p-3  '>
                    <input className=' md:w-1/3 sm:8/12  w-8/12 rounded-md h-10  border-2  border-solid p-5

border-brand-primary '/><SearchOutlinedIcon sx={{
                        fontSize: "37px",
                        alignSelf: "center",
                        marginLeft: "-40px",
                        color: "#6C5CE6"

                    }} />

                </div>
                <div className=' w-11/12 h-max self-center   mt-5 backdrop-blur-3xl flex   gap-x-5  '>
                    <div className=' w-1/3 hidden sm:block'>       <Sidebar /></div>



                    <div className=' w-full  flex-col   max-h-fit  bg-brandv3  px-5 py-3  rounded-lg '>
                        <p className=' text-2xl font-poppins  font-bold  mb-4  text-brand-base/50'>settings</p>

                        <div className=' w-full    h-full flex flex-col md:flex-row'>

                            <div className='md:w-1/2   md:h-5/6 lg:h-4/6  bg-white/90 p-5 flex md:flex-col  rounded-l-2xl justify-between rounded-r-md md:rounded-r-none'>
                                <p className="text-brand-base/50 font-poppins w-max px-2 py-2 rounded-md cursor-pointer hover:bg-brand-primary hover:text-brand-secondary hover:px-4 hover:py-2 hover:rounded-md hover:cursor-pointer hover:text-center">
                                    my profile
                                </p>
                                <p className="text-brand-base/50 font-poppins w-max px-2 py-2 rounded-md cursor-pointer hover:bg-brand-primary hover:text-brand-secondary hover:px-4 hover:py-1 hover:rounded-md hover:cursor-pointer hover:text-center">
                                    security
                                </p>
                                <div className="flex-grow"></div>
                                <p className=" hidden md:block text-brand-base/50 font-poppins   w-max px-2 py-2 rounded-md cursor-pointer hover:bg-red-300 hover:text-brand-secondary hover:px-4 hover:py-2 hover:rounded-md hover:cursor-pointer hover:text-center">
                                    Delete Account
                                </p>
                            </div>

                            <div className='    w-full   mt-4 md:mt-0  md:h-5/6 lg:h-4/6 bg-white rounded-r-xl border border-l border-l-branv2/10 md:rounded-l-none rounded-l-xl  '>
                                <p className=' p-4 text-brand-base/60   font-openSans'>My Profile</p>
                                <div className='w-full flex  p-5 gap-3 border-b border-b-brand-base/10 lg:flex-row flex-col'>
                                    <div className='w-20 h-20  self-start bg-center bg-cover' style={{ aspectRatio: "1 / 1" }}>
                                        <img src="https://images.pexels.com/photos/12903578/pexels-photo-12903578.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" alt="Profile" className="w-full h-full object-cover rounded-full" />
                                    </div>


                                    <div className='flex flex-col'>
                                        <p className='self-start pt-1 text-sm text-brand-base font-poppins'>John doe</p>
                                        <p className='self-start pt-1 text-xs text-brand-base/70 font-poppins'>300 Followers</p>
                                        <p className='self-start pt-1 text-xs text-brand-base/50 font-poppins text-start'>Lorem ipsum dolor sit amet consectetur.</p>
                                    </div>
                                    <div className='flex lg:flex-col lg:ml-auto'>
                                        <p className='  md:self-end text-sm font-poppins rounded-md bg-brand-secondary w-max  text-center text-brand-primary hover:bg-brand-primary/70 hover:px-4 hover:py-2 hover:text-brand-secondary hover:text-center'>
                                            Edit <ModeEditOutlineOutlinedIcon sx={{
                                                fontSize: "15px",
                                                color: "#747474",
                                                '&:hover': { color: '#fff' }
                                            }} />
                                        </p>
                                    </div>
                                </div>

                                <div className=' w-full    '>
                                    <p className=' p-4 text-brand-base/60   font-openSans'>Personal Infromation</p>
                                    <div className='flex   flex-col lg:flex-row gap-4 p-5  justify-between '>
                                        <div>
                                            <p>Full Name</p>
                                            <p className=' text-brand-base/60'> jon doe </p>

                                        </div>
                                        <div>
                                            <p>Email</p>
                                            <p className=' text-brand-base/60'> jon@example.co </p>
                                        </div>
                                        <div>
                                            <p className='self-end text-sm font-poppins rounded-md bg-brand-secondary w-max text-center text-brand-primary hover:bg-brand-primary/70 hover:px-4 hover:py-2 hover:text-brand-secondary hover:text-center'>
                                                Edit <ModeEditOutlineOutlinedIcon sx={{
                                                    fontSize: "15px",
                                                    color: "#747474",
                                                    '&:hover': { color: '#fff' }
                                                }} />
                                            </p>

                                        </div>

                                    </div>



                                </div>
                            </div>
                            <p className="text-brand-base/50 font-poppins  block md:hidden   w-max px-2 py-2 rounded-md cursor-pointer hover:bg-red-300 hover:text-brand-secondary hover:px-4 hover:py-2 hover:rounded-md hover:cursor-pointer hover:text-center mt-5" >
                                Delete Account
                            </p>
                        </div>


                    </div>

                </div>
            </main>
        </>
    )
}
