
import Nav from '../components/Nav'
import Head from 'next/head'
import SearchOutlinedIcon from '@mui/icons-material/SearchOutlined';
import Sidebar from "../components/userdashboard/Sidebar";
import BlogCard from '../components/index/BlogCard';
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>postcases</title>

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.15.1/devicon.min.css" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='    w-fit h-max flex flex-col'>
        <Nav />
        <div className='w-full h-max  b flex justify-center mt-5   p-3  '>
          <input className=' md:w-1/3 sm:8/12  w-8/12 rounded-md h-10  border-2  border-solid p-5

border-brand-primary '/><SearchOutlinedIcon sx={{
            fontSize: "37px",
            alignSelf: "center",
            marginLeft: "-40px",
            color: "#6C5CE6"

          }} />

        </div>
        <div className=' w-11/12 h-max self-center   mt-5 backdrop-blur-3xl flex   gap-x-5  '>
          <div className=' w-1/3 hidden sm:block'>       <Sidebar /></div>



          <div className=' w-full flex  flex-col gap-3'>
            <div className=' w-full h-max bg-brandv3/30 flex flex-col    p-6'>
              <div className='  w-24   h-24 rounded-full bg-[url("https://images.pexels.com/photos/12903578/pexels-photo-12903578.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2")] bg-brand-primary self-center bg-center bg-cover border border-brand-primary'></div>
              <p className=' self-center pt-1   text-sm  text-brand-base font-poppins '>John doe</p>
              <p className=' self-center pt-1   text-xs  text-brand-base/70 font-poppins '>300 Followers</p>
              <p className=' self-center pt-1   text-xs  text-brand-base/50 font-poppins  text-center'>Lorem ipsum dolor sit amet consectetur.</p>
              <button className=' w-max px-5  bg-brand-primary py-2   rounded-lg mt-3 text-base font-roboto   text-brand-secondary self-center '>Update Bio</button>
            </div>
            {/* <MobileCard />

            <Card />
            <Card />
            <Card /> */}
            <p className=' text-2xl  font-bold  '>List of Your post</p>
            <Link href="/SinglePost">
              <BlogCard />
            </Link>
            <Link href="/SinglePost">
              <BlogCard />
            </Link>
            <Link href="/SinglePost">
              <BlogCard />
            </Link>
            <Link href="/SinglePost">
              <BlogCard />
            </Link>
            <Link href="/SinglePost">
              <BlogCard />
            </Link>
            <Link href="/SinglePost">
              <BlogCard />
            </Link>
            <Link href="/SinglePost">
              <BlogCard />
            </Link>
            <Link href="/SinglePost">
              <BlogCard />
            </Link>




          </div>

        </div>
      </main>
    </>
  )
}
